exports.messageConstants = {
  signupSuccess: "User signup successfully.",
  signupSuccessTherapist: "Therapist signup successfully.",
  outletSuccessTherapist: "Outlet signup successfully.",
  passwordChanged: "Password changed successfully.",
  emailAlreadyExists: "Email already exists.",
  emailAlreadyVerified: "Email already verified.",
  emailVerificationSuccess: "Email verified successfully.",
  invalidOtp: "Invalid OTP.",
  invalidEmailOrPassword: "Invalid email or password.",
  emailNotVerified: "Your email is not verified.",
  accountBlocked: "Your account is blocked by administrator.",
  loginSuccess: "Logged in successfully.",
  forgotPasswordOtpShared: "Otp shared to your registred e-mail id.",
  sessionExpired: "Session expired, request again for otp.",
  comparePassword: "Old password is incorrect.",
  userNotFound: "User not found.",
  therapistNotFound: "Therapist not found.",
  appointmentNotFound: "Appointment not found.",
  bookedAppointmentSuccess: "Appointment booked successfully.",
  profileRegister: "Profile registered successfully.",
  appointmentsfound: "Appointments found.",
  serverIssue: "Internal Server Error.",
  appointmentCancelSuccess: "Appointments have been successfully canceled.",
  appointmentCancelFailed: "Oops! We encountered a problem while canceling appointments. Please try again later or contact support for assistance.",
  appointmentCompleted: "Appointment completed",
  sessionCompleted: "Session completed successfully.",
  sessionCompletedReq: "Request to complete session successfully.",
  sessionCompletedCanceled: "Request to complete session canceled successfully.",
  sessionBeginReq: "Request to start session successfully.",
  sessionBegin: "Session begin successfully.",
  sessionBeginCanceled: "Request to start session canceled successfully.",
  sessionNotExsist: "Session does not exist.",
  sessionnotCompleted: "Session completion failed.",
  sessionCanceled: "Session canceled successfully.",
  sessionUpgraded: "Session upgraded successfully.",
  sessionUpgradedFailed: "Session upgraded failed.",
  sessionTerminated: "Session terminated successfully"
};
